/**
 * Crear Reporte Tool - Voice formatted report creation
 */

import {
  createTicket,
  getCategoryId,
  getSubcategoryId,
  type CategoryCode,
} from "../services/database.js";
import { formatFolioForVoice, spellDigits } from "../utils/number-to-words.js";
import { REPORT_TYPE_VOICE, VOICE_CONFIG } from "../config/voice-agent.js";

type ReportType = "fuga_via_publica" | "fuga_medidor" | "drenaje" | "sin_agua" | "calidad_agua" | "otro";

interface CrearReporteInput {
  tipo: ReportType;
  ubicacion: string;
  descripcion: string;
  contrato?: string;
}

interface CrearReporteResult {
  success: boolean;
  response: string;
  data?: {
    folio: string;
    tipo: string;
  };
}

// Map report types to category/subcategory codes
const REPORT_MAPPINGS: Record<
  ReportType,
  { category: CategoryCode; subcategory: string; title: string; priority: "low" | "medium" | "high" | "urgent" }
> = {
  fuga_via_publica: {
    category: "REP",
    subcategory: "REP-FVP",
    title: "Fuga en vía pública",
    priority: "high",
  },
  fuga_medidor: {
    category: "REP",
    subcategory: "REP-FMD",
    title: "Fuga en medidor",
    priority: "high",
  },
  drenaje: {
    category: "REP",
    subcategory: "REP-DRN",
    title: "Problema de drenaje",
    priority: "high",
  },
  sin_agua: {
    category: "REP",
    subcategory: "REP-SAG",
    title: "Falta de agua",
    priority: "urgent",
  },
  calidad_agua: {
    category: "REP",
    subcategory: "REP-CAL",
    title: "Calidad del agua",
    priority: "medium",
  },
  otro: {
    category: "REP",
    subcategory: "REP-OTR",
    title: "Otro reporte",
    priority: "medium",
  },
};

/**
 * Create a report and return voice-formatted response
 */
export async function crearReporte(input: CrearReporteInput): Promise<CrearReporteResult> {
  const { tipo, ubicacion, descripcion } = input;
  // Normalize contract number if provided - remove spaces, hyphens, and non-digits
  const contrato = input.contrato ? input.contrato.replace(/[^0-9]/g, "") : undefined;
  console.log(`[crear_reporte] Creating report: ${tipo} at ${ubicacion}${contrato ? ` (contract: ${contrato})` : ""}`);

  try {
    const mapping = REPORT_MAPPINGS[tipo] || REPORT_MAPPINGS.otro;
    const tipoVoz = REPORT_TYPE_VOICE[tipo] || tipo;

    // Get category and subcategory IDs
    const categoryId = await getCategoryId(mapping.category);
    const subcategoryId = await getSubcategoryId(mapping.subcategory);

    if (!categoryId) {
      throw new Error("Category not found");
    }

    // Create the ticket (folio is auto-generated by database trigger)
    const ticket = await createTicket({
      title: mapping.title,
      description: `${descripcion}\n\nUbicación: ${ubicacion}${contrato ? `\nContrato: ${contrato}` : ""}\n\n[Reporte creado por voz]`,
      categoryId,
      subcategoryId,
      contractNumber: contrato || null,
      priority: mapping.priority,
      ubicacion,
      metadata: {
        channel: "voice",
        tipo,
        report_type: mapping.subcategory,
      },
    });

    const folio = ticket.folio;

    // Build voice response
    const folioVoz = formatFolioForVoice(folio);

    let response = `Listo, registré tu reporte de ${tipoVoz} con folio ${folioVoz}.`;

    // Add follow-up info based on type
    if (tipo === "fuga_via_publica" || tipo === "drenaje") {
      response += ` Un técnico lo revisará en las próximas veinticuatro horas.`;
    } else if (tipo === "sin_agua") {
      response += ` Este reporte tiene prioridad urgente, lo atenderemos lo antes posible.`;
    } else {
      response += ` Te notificaremos cuando tengamos actualizaciones.`;
    }

    // Suggest photo via WhatsApp
    response += ` Si tienes foto del problema, envíala por WhatsApp al ${VOICE_CONFIG.whatsappNumber} mencionando el folio.`;

    return {
      success: true,
      response,
      data: {
        folio,
        tipo: tipoVoz,
      },
    };
  } catch (error) {
    console.error(`[crear_reporte] Error:`, error);

    return {
      success: false,
      response:
        "No pude registrar tu reporte en este momento. Por favor llama al cuatro cuatro dos, dos tres ocho, ocho dos cero cero para reportarlo directamente.",
    };
  }
}

export default crearReporte;
