#!/bin/bash
# ============================================
# Sync Secrets from GCP Secret Manager
# Pulls secrets into .env files for both stacks
# ============================================
#
# Usage:
#   bash deploy/sync-secrets.sh
#
# Prerequisites:
#   - Running on a GCE instance with Secret Manager access
#   - Or: gcloud auth configured with secretmanager.versions.access
#
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE} Sync Secrets from GCP Secret Manager       ${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

# --- Detect GCP project ID ---
if [ -n "${GCP_PROJECT_ID:-}" ]; then
    PROJECT_ID="$GCP_PROJECT_ID"
elif curl -sf -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/project/project-id" >/dev/null 2>&1; then
    PROJECT_ID=$(curl -sf -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/project/project-id")
else
    PROJECT_ID=$(gcloud config get-value project 2>/dev/null || true)
fi

if [ -z "$PROJECT_ID" ]; then
    echo -e "${RED}Could not determine GCP project ID.${NC}"
    echo "Set GCP_PROJECT_ID or run on a GCE instance."
    exit 1
fi

echo "GCP Project: $PROJECT_ID"
echo ""

# --- Helper: fetch a secret ---
fetch_secret() {
    local secret_name="$1"
    local default_value="${2:-}"

    local value
    value=$(gcloud secrets versions access latest \
        --secret="$secret_name" \
        --project="$PROJECT_ID" 2>/dev/null || true)

    if [ -z "$value" ]; then
        if [ -n "$default_value" ]; then
            echo "$default_value"
            return 0
        fi
        echo -e "  ${YELLOW}!${NC} Secret '$secret_name' not found" >&2
        echo ""
        return 0
    fi
    echo "$value"
}

# --- Build gobierno-queretaro/.env ---
echo -e "${GREEN}Syncing gobierno-queretaro/.env...${NC}"

GOBIERNO_ENV="$PROJECT_DIR/gobierno-queretaro/.env"

cat > "$GOBIERNO_ENV" << ENVEOF
# ============================================
# Gobierno Queretaro - Environment Variables
# Generated by sync-secrets.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ============================================

# Anthropic API Key
ANTHROPIC_API_KEY=$(fetch_secret "anthropic-api-key")

# CEA Proxy & SOAP credentials
CEA_PROXY_URL=$(fetch_secret "cea-proxy-url")
CEA_SOAP_USERNAME=$(fetch_secret "cea-soap-username" "WSGESTIONDEUDA")
CEA_SOAP_PASSWORD=$(fetch_secret "cea-soap-password" "WSGESTIONDEUDA")

# Log level
LOG_LEVEL=INFO

# Voice Gateway
ELEVENLABS_API_KEY=$(fetch_secret "elevenlabs-api-key")
DEEPGRAM_API_KEY=$(fetch_secret "deepgram-api-key")
ELEVENLABS_VOICE_ID=cgSgspJ2msm6clMCkdW9
ELEVENLABS_MODEL_ID=eleven_turbo_v2
DEEPGRAM_MODEL=nova-2
DEEPGRAM_LANGUAGE=es-419

# PACO Admin API
PACO_ADMIN_API_KEY=$(fetch_secret "paco-admin-api-key")

# Paco JWT Secret
PACO_JWT_SECRET=$(fetch_secret "paco-jwt-secret")

# Encryption key
ENCRYPTION_KEY=$(fetch_secret "encryption-key")

# Rate Limiting
RATE_LIMIT_ROUTE=60/minute
RATE_LIMIT_CLASSIFY=120/minute

# Chatwoot (optional)
CHATWOOT_API_KEY=$(fetch_secret "chatwoot-api-key")
ENVEOF

chmod 600 "$GOBIERNO_ENV"
echo -e "  ${GREEN}OK${NC} $GOBIERNO_ENV"

# --- Build paco/.env ---
echo -e "${GREEN}Syncing paco/.env...${NC}"

PACO_ENV="$PROJECT_DIR/paco/.env"

cat > "$PACO_ENV" << ENVEOF
# ============================================
# PACO Agent Hub - Environment Configuration
# Generated by sync-secrets.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ============================================

# PostgreSQL
POSTGRES_USER=paco
POSTGRES_PASSWORD=$(fetch_secret "postgres-password-paco")
POSTGRES_DB=paco

# Langfuse
LANGFUSE_URL=http://localhost:3001
LANGFUSE_NEXTAUTH_SECRET=$(fetch_secret "langfuse-nextauth-secret")
LANGFUSE_SALT=$(fetch_secret "langfuse-salt")
LANGFUSE_ENCRYPTION_KEY=$(fetch_secret "langfuse-encryption-key")
LANGFUSE_TELEMETRY=false
LANGFUSE_PUBLIC_KEY=$(fetch_secret "langfuse-public-key")
LANGFUSE_SECRET_KEY=$(fetch_secret "langfuse-secret-key")

# PACO Backend
PACO_SECRET_KEY=$(fetch_secret "paco-secret-key")
PACO_API_URL=http://localhost:8000
CORS_ORIGINS=https://paco.YOUR-DOMAIN,https://langfuse.YOUR-DOMAIN

# PACO Frontend
PACO_URL=https://paco.YOUR-DOMAIN
PACO_NEXTAUTH_SECRET=$(fetch_secret "paco-nextauth-secret")

# CEA Tools
CEA_API_URL=$(fetch_secret "cea-api-url")
CEA_API_USER=$(fetch_secret "cea-api-user")
CEA_API_PASSWORD=$(fetch_secret "cea-api-password")

# Agent Keys
ELEVENLABS_API_KEY=$(fetch_secret "elevenlabs-api-key")
ANTHROPIC_API_KEY=$(fetch_secret "anthropic-api-key")

# Chatwoot
CHATWOOT_API_KEY=$(fetch_secret "chatwoot-api-key")
CHATWOOT_BASE_URL=$(fetch_secret "chatwoot-base-url")
ENVEOF

chmod 600 "$PACO_ENV"
echo -e "  ${GREEN}OK${NC} $PACO_ENV"

echo ""
echo -e "${GREEN}Secrets synced successfully.${NC}"
echo ""
echo -e "${YELLOW}Remember to update YOUR-DOMAIN placeholders in paco/.env${NC}"
echo "if this is a fresh deployment."
