/**
 * PostgreSQL database service for maria-voz
 */

import pg from 'pg';

// Database configuration from environment
const PG_CONFIG = {
  host: process.env.PGHOST || 'localhost',
  port: parseInt(process.env.PGPORT || '5432'),
  user: process.env.PGUSER || 'postgres',
  password: process.env.PGPASSWORD || '',
  database: process.env.PGDATABASE || 'agora_production',
  max: parseInt(process.env.PGPOOL_MAX || '10'),
};

// Create pool instance
const pool = new pg.Pool(PG_CONFIG);

// Handle pool errors
pool.on('error', (err) => {
  console.error('[DB] Unexpected pool error:', err);
});

/**
 * Generic query wrapper with automatic connection management
 */
export async function pgQuery<T = Record<string, unknown>>(
  query: string,
  params?: unknown[]
): Promise<T[]> {
  const client = await pool.connect();
  try {
    const result = await client.query(query, params);
    return result.rows as T[];
  } finally {
    client.release();
  }
}

/**
 * Get Mexico City timezone date
 */
export function getMexicoDate(): Date {
  return new Date(
    new Date().toLocaleString('en-US', { timeZone: 'America/Mexico_City' })
  );
}

// Types
export interface Ticket {
  id: number;
  folio: string;
  title: string;
  description: string;
  status: string;
  priority: string;
  ticket_category_id: number;
  ticket_subcategory_id: number | null;
  contract_number: string | null;
  created_at: Date;
  updated_at: Date;
  // Joined fields
  category_code?: string;
  category_name?: string;
}

export interface TicketCategory {
  id: number;
  code: string;
  name: string;
}

export interface Contact {
  id: number;
  name: string;
  phone_number: string;
  identifier: string;
  custom_attributes: Record<string, unknown>;
}

export type CategoryCode = 'CON' | 'FAC' | 'CTR' | 'CVN' | 'REP' | 'SRV' | 'CNS';

// CEA account ID (hardcoded for CEA Querétaro)
const ACCOUNT_ID = 2;

/**
 * Get category ID by code
 */
export async function getCategoryId(code: CategoryCode): Promise<number | null> {
  const result = await pgQuery<TicketCategory>(
    `SELECT id FROM ticket_categories WHERE code = $1 AND account_id = $2`,
    [code, ACCOUNT_ID]
  );
  return result.length > 0 ? result[0].id : null;
}

/**
 * Get subcategory ID by code
 * Note: subcategories don't have account_id, so we join with categories
 */
export async function getSubcategoryId(code: string): Promise<number | null> {
  const result = await pgQuery<{ id: number }>(
    `SELECT ts.id FROM ticket_subcategories ts
     JOIN ticket_categories tc ON ts.ticket_category_id = tc.id
     WHERE ts.code = $1 AND tc.account_id = $2`,
    [code, ACCOUNT_ID]
  );
  return result.length > 0 ? result[0].id : null;
}

/**
 * Get tickets by contract number
 */
export async function getTicketsByContract(contractNumber: string): Promise<Ticket[]> {
  return pgQuery<Ticket>(
    `SELECT t.*, tc.code as category_code, tc.name as category_name
     FROM tickets t
     LEFT JOIN ticket_categories tc ON t.ticket_category_id = tc.id
     WHERE t.contract_number = $1 AND t.account_id = $2
     ORDER BY t.created_at DESC
     LIMIT 10`,
    [contractNumber, ACCOUNT_ID]
  );
}

/**
 * Create a new ticket
 * Note: folio is auto-generated by database trigger (format: CEA-XXXXX)
 */
export async function createTicket(data: {
  title: string;
  description: string;
  categoryId: number;
  subcategoryId?: number | null;
  contractNumber?: string | null;
  priority?: string;
  ubicacion?: string | null;
  metadata?: Record<string, unknown>;
}): Promise<Ticket> {
  const {
    title,
    description,
    categoryId,
    subcategoryId = null,
    contractNumber = null,
    priority = 'medium',
    ubicacion = null,
    metadata = {}
  } = data;

  const result = await pgQuery<Ticket>(
    `INSERT INTO tickets (
      title, description, status, priority,
      ticket_category_id, ticket_subcategory_id, contract_number,
      account_id, metadata, created_at, updated_at
    ) VALUES ($1, $2, 'open', $3, $4, $5, $6, $7, $8, NOW(), NOW())
    RETURNING *`,
    [
      title,
      description,
      priority,
      categoryId,
      subcategoryId,
      contractNumber,
      ACCOUNT_ID,
      JSON.stringify(metadata)
    ]
  );

  return result[0];
}

/**
 * Search customer by contract number
 */
export async function searchCustomerByContract(
  contractNumber: string
): Promise<Contact | null> {
  const result = await pgQuery<Contact>(
    `SELECT * FROM contacts
     WHERE identifier = $1
     OR custom_attributes->>'contract_number' = $1
     LIMIT 1`,
    [contractNumber]
  );
  return result.length > 0 ? result[0] : null;
}

/**
 * Close database pool (for graceful shutdown)
 */
export async function closePool(): Promise<void> {
  await pool.end();
}
