'use client';

import React, { useEffect, useState } from 'react';
import { Modal, Tabs, Button, message, Spin } from 'antd';
import { Download, FileCode, FileText, Package } from 'lucide-react';
import { CodePreview } from '../code-generation';
import { workflowToIR, generateTypeScriptCode } from '../code-generation';
import { downloadFile, downloadZip, toSafeFilename } from './download-utils';
import { api } from '@/lib/api';
import { CustomNode, CustomEdge } from '../types';

interface ExportModalProps {
  open: boolean;
  onClose: () => void;
  nodes: CustomNode[];
  edges: CustomEdge[];
  workflowName: string;
  workflowDescription?: string;
}

export function ExportModal({
  open,
  onClose,
  nodes,
  edges,
  workflowName,
  workflowDescription,
}: ExportModalProps) {
  const [activeTab, setActiveTab] = useState<'typescript' | 'python'>('typescript');
  const [tsCode, setTsCode] = useState<string>('');
  const [pyCode, setPyCode] = useState<string>('');
  const [pyRequirements, setPyRequirements] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Generate code when modal opens
  useEffect(() => {
    if (!open) return;

    const generateCode = async () => {
      setLoading(true);
      setError(null);

      try {
        // Transform workflow to IR
        const ir = workflowToIR(
          nodes,
          edges,
          workflowName || 'My Agent',
          workflowDescription
        );

        // Generate TypeScript (client-side)
        const typescript = generateTypeScriptCode(ir);
        setTsCode(typescript);

        // Generate Python (server-side)
        // Cast IR to the API's expected type (structurally compatible at runtime)
        const pythonResponse = await api.generatePythonCode(ir as Parameters<typeof api.generatePythonCode>[0]);
        setPyCode(pythonResponse.code);

        const requirementsResponse = await api.getPythonRequirements({ name: ir.name });
        setPyRequirements(requirementsResponse.code);
      } catch (err: any) {
        console.error('Code generation error:', err);
        setError(err.message || err.detail || 'Failed to generate code');
      } finally {
        setLoading(false);
      }
    };

    generateCode();
  }, [open, nodes, edges, workflowName, workflowDescription]);

  const handleDownloadTs = () => {
    const filename = `${toSafeFilename(workflowName)}.ts`;
    downloadFile(tsCode, filename);
    message.success(`Downloaded ${filename}`);
  };

  const handleDownloadPy = () => {
    const filename = `${toSafeFilename(workflowName)}.py`;
    downloadFile(pyCode, filename);
    message.success(`Downloaded ${filename}`);
  };

  const handleDownloadPyZip = async () => {
    const baseName = toSafeFilename(workflowName);
    await downloadZip(
      [
        { name: `${baseName}.py`, content: pyCode },
        { name: 'requirements.txt', content: pyRequirements },
        { name: 'README.md', content: generateReadme(workflowName, workflowDescription) },
      ],
      `${baseName}-python.zip`
    );
    message.success(`Downloaded ${baseName}-python.zip`);
  };

  const generateReadme = (name: string, description?: string) => {
    return `# ${name}

${description || 'Claude Agent generated by PACO Visual Agent Builder'}

## Setup

1. Install dependencies:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`

2. Set your Anthropic API key:
   \`\`\`bash
   export ANTHROPIC_API_KEY=your-api-key
   \`\`\`

3. Run the agent:
   \`\`\`bash
   python ${toSafeFilename(name)}.py
   \`\`\`

## Customization

Edit the \`prompt\` parameter in the script to specify your task.

---
Generated by [PACO Visual Agent Builder](https://github.com/your-org/paco)
`;
  };

  const tabItems = [
    {
      key: 'typescript',
      label: (
        <span className="flex items-center gap-2">
          <FileCode size={16} />
          TypeScript
        </span>
      ),
      children: (
        <div>
          <CodePreview
            code={tsCode}
            language="typescript"
            height="350px"
          />
          <div className="mt-4 flex justify-end">
            <Button
              icon={<Download size={16} />}
              onClick={handleDownloadTs}
              disabled={!tsCode}
            >
              Download .ts
            </Button>
          </div>
        </div>
      ),
    },
    {
      key: 'python',
      label: (
        <span className="flex items-center gap-2">
          <FileText size={16} />
          Python
        </span>
      ),
      children: (
        <div>
          <CodePreview
            code={pyCode}
            language="python"
            height="350px"
          />
          <div className="mt-4 flex justify-end gap-2">
            <Button
              icon={<Download size={16} />}
              onClick={handleDownloadPy}
              disabled={!pyCode}
            >
              Download .py
            </Button>
            <Button
              type="primary"
              icon={<Package size={16} />}
              onClick={handleDownloadPyZip}
              disabled={!pyCode}
            >
              Download Zip (with requirements)
            </Button>
          </div>
        </div>
      ),
    },
  ];

  return (
    <Modal
      title="Export Agent Code"
      open={open}
      onCancel={onClose}
      footer={null}
      width={700}
      destroyOnClose
    >
      {loading ? (
        <div className="flex items-center justify-center py-12">
          <Spin size="large" />
          <span className="ml-4">Generating code...</span>
        </div>
      ) : error ? (
        <div className="text-red-500 py-8 text-center">
          <p className="font-medium">Error generating code</p>
          <p className="text-sm mt-2">{error}</p>
          <Button onClick={onClose} className="mt-4">
            Close
          </Button>
        </div>
      ) : (
        <Tabs
          activeKey={activeTab}
          onChange={(key) => setActiveTab(key as 'typescript' | 'python')}
          items={tabItems}
        />
      )}
    </Modal>
  );
}
