/**
 * TypeScript Code Generation from WorkflowIR
 *
 * Generates valid TypeScript code using Claude Agent SDK patterns.
 * The generated code uses the async iterator pattern (for await...of query()).
 */

import { WorkflowIR, McpServerIR, KnowledgeSourceIR } from './ir';

/**
 * Escape backticks and $ in template strings for safe embedding
 */
function escapeTemplateString(str: string): string {
  return str.replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

/**
 * Generate knowledge sources documentation comment block
 */
function generateKnowledgeSourcesComment(sources: KnowledgeSourceIR[]): string {
  if (sources.length === 0) return '';

  const sourceLines = sources.map((source) => {
    const typeLabel = source.type.charAt(0).toUpperCase() + source.type.slice(1);
    const sourcesList = source.sources.join(', ');
    return ` * - ${typeLabel}: ${source.name} (${sourcesList})`;
  });

  return `/**
 * Knowledge Sources (for manual RAG integration):
${sourceLines.join('\n')}
 *
 * Note: Claude Agent SDK does not include built-in RAG.
 * Integrate these sources using your preferred retrieval system.
 */

`;
}

/**
 * Generate MCP servers configuration object
 */
function generateMcpServersConfig(servers: McpServerIR[]): string {
  if (servers.length === 0) return '';

  const serverEntries = servers
    .map((server) => {
      if (server.type === 'stdio') {
        const argsJson = JSON.stringify(server.args || []);
        let config = `      "${server.name}": {\n        command: "${server.command}",\n        args: ${argsJson}`;

        if (server.env && Object.keys(server.env).length > 0) {
          config += `,\n        env: ${JSON.stringify(server.env)}`;
        }

        config += '\n      }';
        return config;
      } else {
        // SSE or HTTP
        return `      "${server.name}": {\n        type: "${server.type}",\n        url: "${server.url}"\n      }`;
      }
    })
    .join(',\n');

  return `mcpServers: {\n${serverEntries}\n    },`;
}

/**
 * Generate allowedTools array combining built-in tools and MCP tools
 */
function generateAllowedTools(ir: WorkflowIR): string {
  const tools: string[] = [...(ir.allowedTools || [])];

  // Add MCP tool references
  for (const server of ir.mcpServers) {
    if (server.enabledTools.length > 0) {
      // Specific tools enabled
      tools.push(...server.enabledTools.map((t) => `mcp__${server.name}__${t}`));
    } else {
      // Wildcard - all tools from server
      tools.push(`mcp__${server.name}__*`);
    }
  }

  if (tools.length === 0) return '';

  const toolsJson = JSON.stringify(tools);
  return `allowedTools: ${toolsJson},`;
}

/**
 * Generate TypeScript code from WorkflowIR
 *
 * @param ir - The intermediate representation of the workflow
 * @returns Valid TypeScript code string using Claude Agent SDK
 */
export function generateTypeScriptCode(ir: WorkflowIR): string {
  const { name, description, agent, mcpServers, permissionMode, knowledgeSources } = ir;

  // Generate optional sections
  const knowledgeComment = generateKnowledgeSourcesComment(knowledgeSources);
  const mcpServersCode = generateMcpServersConfig(mcpServers);
  const allowedToolsCode = generateAllowedTools(ir);

  // Build options object entries
  const optionLines: string[] = [];

  if (agent.systemPrompt) {
    const escapedPrompt = escapeTemplateString(agent.systemPrompt);
    optionLines.push(`      systemPrompt: \`${escapedPrompt}\`,`);
  }

  if (agent.model) {
    optionLines.push(`      model: "${agent.model}",`);
  }

  if (mcpServersCode) {
    optionLines.push(`      ${mcpServersCode}`);
  }

  if (allowedToolsCode) {
    optionLines.push(`      ${allowedToolsCode}`);
  }

  optionLines.push(`      permissionMode: "${permissionMode}"`);

  const optionsBlock = optionLines.join('\n');

  // Generate the full code
  const code = `import { query } from "@anthropic-ai/claude-agent-sdk";

${knowledgeComment}/**
 * ${name}
 * ${description || 'Generated by PACO Visual Agent Builder'}
 */

async function main() {
  for await (const message of query({
    prompt: "YOUR_PROMPT_HERE",
    options: {
${optionsBlock}
    }
  })) {
    if (message.type === "assistant") {
      for (const block of message.message?.content || []) {
        if ("text" in block) {
          console.log(block.text);
        }
      }
    }
    if (message.type === "result" && message.subtype === "success") {
      console.log("\\nTask completed:", message.result);
    }
  }
}

main().catch(console.error);
`;

  return code;
}
